#!/bin/sh
set -o errexit

##
# Publish our gem to our local host, 
# tpyically our own sixarm.com website.
#
# Example:
#   cd mygem
#   gemforge-publish-to-local-host
#   => copies all the gem's files to our local host
##

# Get the current directory's gem info
gem_name=`gemspec-cat | gemspec-to-gem-name`
gem_name_version=`gemspec-cat | gemspec-to-gem-name-version`

# Where on the local host to put the gem directory
dst=/var/www/sixarm.com/html
gem_generate_directory=$dst/gems

# Sync all the gem files
rsync --recursive -C --hard-links --exclude='.git/' --executability --delete --times * $dst/$gem_name/

# Also, put the gem file in the /gems directory so it can be built
rsync *.gem $gem_generate_directory/

# Generate
gem generate --backtrace --directory=$gem_generate_directory/

