#!/bin/bash
set -o errexit

##
# Do simple checking of our gem's files to ensure
# that everything looks good before we publish.
##

gem_name_version=`gemspec-cat | gemspec-to-gem-name-version`
gem_name=`gemspec-cat | gemspec-to-gem-name`
gem_version=`gemspec-cat | gemspec-to-gem-version`
github_team="SixArm"
github_repo="$gem_name"
github_team_repo="$github_team/$github_repo"
github_link="https://github.com/$github_team_repo"

function err ( ) {
   echo "gemforge-lint $gem_name_version $@" >&2
}

function file_line_should_eq {
  file=$1
  line_num=$2
  expect_line=$3
  actual_line=`sed -n "${line_num}p" "$file"`
  if [ "$expect_line" != "$actual_line" ]
  then
    err "file $file line $line_num\n expect: $expect_line\n actual:$actual_line"
  fi
}

function grepq {
  grep -q "$2" "$1" || err "$1 grep $2"
}

### Repair

# Repair via placeholders
[ -e "VERSION" ] || echo "$gem_version" > VERSION

# Repair via cookie cutter
for path in ".rspec" "Rakefile"
do
  [ -e "$path" ] || cp "/home/sixarm/git/sixarm_ruby_week/$path" .
done

# Repair via building
[ -e "coverage" ] || gemforge-test
[ -e "doc" ] || gemforge-create-doc
[ -e "$gem_name_version.gem" ] || gemforge-build-gemspec
[ -e "$gem_name_version-sha512.txt" ] || gemforge-sha512

# Repair versions
grep -q "^$gem_version$" VERSION || echo "$gem_version" > VERSION

# Fill in
gemforge-fill-in

###

for path in "CHANGELOG.txt" "INSTALL.txt" "LICENSE.txt" "$gem_name.sha512.txt"
do
  [ -e "$path" ] && err "$path should not exist"
done

ls -1 *.gem | wc -l | grep "^ *1$" > /dev/null || err "More than one gem"
ls -1 *sha512.txt | wc -l | grep "^ *1$" > /dev/null || err "More than one sha512"

for path in ".codeclimate.yml" ".document" ".gemtest" ".git" ".rspec" "CONTRIBUTING.md" "Rakefile" "README.md" "VERSION" "coverage" "coverage/assets" "coverage/index.html" "doc" "lib" "lib/${gem_name}.rb" "test" "$gem_name.gemspec" "$gem_name_version.gem" "$gem_name_version-sha512.txt"
do
  [ -e "$path" ] || err "-e $path"
done

file="$gem_name.gemspec"
file_line_should_eq "$file" 1 "# -*- coding: utf-8 -*-"
file_line_should_eq "$file" 2 ""
file_line_should_eq "$file" 3 "Gem::Specification.new do |s|"
for s in \
  "^  s.name           = \"sixarm_ruby_.*\"" \
  "^  s.summary        = \"SixArm.com » Ruby » .*\"" \
  "^  s.description    = \".*\"" \
  "^  s.version        = \".*\"" \
  "^  s.author         = \"SixArm\"" \
  "^  s.email          = \"sixarm@sixarm.com\"" \
  "^  s.homepage       = \"http://sixarm.com/\"" \
  "^  s.licenses       = \[.*\]" \
  "^  s.signing_key    =  \".*/sixarm-rsa-4096-x509-20150314-private.pem\"" \
  "^  s.cert_chain     = \[\".*/sixarm-rsa-4096-x509-20150314-public.pem\"\]" \
  "^  s.platform       = Gem::Platform::RUBY" \
  "^  s.require_path   = \"lib\"" \
  "^  s.has_rdoc       = true" \
  "^  s.files = \[" \
  "^    \".gemtest\"," \
  "^    \"CHANGES.md\"," \
  "^    \"CONTRIBUTING.md\"," \
  "^    \"LICENSE.md\"," \
  "^    \"Rakefile\"," \
  "^    \"README.md\"," \
  "^    \"VERSION\"," \
  "^  s.test_files = \["
do
  grepq "$file" "$s"
done

file="VERSION"
grep -q "^$gem_version$" $file || err "$file version is wrong"

file="README.md"
for s in \
  "^# SixArm.com » Ruby » <br> " \
  "^\[!\[Code Climate\].*https://codeclimate.com/github/$github_team_repo.png.*https://codeclimate.com/github/$github_team_repo" \
  "^\[!\[Build Status\].*https://travis-ci.org/$github_team_repo.png.*https://travis-ci.org/$github_team_repo" \
  "^* Doc: <http://sixarm.com/$gem_name/doc>" \
  "^* Gem: <http://rubygems.org/gems/$gem_name>" \
  "^* Repo: <http://github.com/sixarm/$gem_name>" \
  "^* Email: Joel Parker Henderson, <joel@sixarm.com>" \
  "^## Introduction" \
  "^For docs go to <http://sixarm.com/$gem_name/doc>" \
  "^## Install quickstart" \
  "^    gem install $gem_name" \
  "^    gem \"$gem_name\", \">=$gem_version\", \"<.*\"" \
  "^    require \"$gem_name\"" \
  "^## Install with security (optional)" \
  "^    gem install $gem_name --trust-policy HighSecurity"
do
  grepq "$file" "$s"
done

file="CHANGES.md"
grep -q "^# Changes$" $file || err "$file headline is wrong"
grep -q '^\* 2015-07-07 .* Update gemspec to use file manifest' $file || err "$file missing update. Please add update."
cat $file | grep -v ' etc\.$' | grep -q '\.$' && err "$file has line that ends in period. Please delete period."

file="LICENSE.md"
grep -q '^# License$' $file || err "$file headline is wrong"

#grep -q '^Author::\( Joel Parker Henderson, joel@joelparkerhenderson.com\| Found on the internet by Joel Parker Henderson, joel@joelparkerhenderson.com\)' $file || err "$file author is wrong"
#  "^\(Copyright (c) Joel Parker Henderson\| Copyright the original author; please email me if you know who wrote this\)" \

exit 0 #TODO REMOVE THIS LINE WHEN ALL THE GEMS VALIDATE THUS FAR

###
#
# Lint each of the deeper files
#
###

for file in `find lib -type f -name "*.rb"`
do
    file_line_should_eq "$file" 1 "# -*- coding: utf-8 -*-"
done

for file in `find test -type f -name "*_test.rb"`
do
    file_line_should_eq "$file" 1 "# -*- coding: utf-8 -*-"
    file_line_should_eq "$file" 2 "require \"minitest/autorun\""
    file_line_should_eq "$file" 3 "Minitest::Test ||= MiniTest::Unit::TestCase"
    file_line_should_eq "$file" 4 "require \"simplecov\""
    file_line_should_eq "$file" 5 "SimpleCov.start"
done

exit 0
