#!/bin/sh
set -o errexit

##
# Publish our gem to our remote host, 
# tpyically our own sixarm.com website.
#
# Example:
#   cd mygem
#   gemforge-publish-to-remote-host
#   => signs into remote host and does a git pull
##

# Local: get the current directory's gem info
gem_name=`gemspec-cat | gemspec-to-gem-name`
gem_name_version=`gemspec-cat | gemspec-to-gem-name-version`

# Config: destination settings for our remote host
dst_user=sixarm
dst_host=www.sixarm.com
dst_path=/var/www/sixarm.com/html/
dst_path_gem_name="$dst_path/$gem_name"
dst_port=22
git_deploy_link=git://github.com/SixArm/$gem_name.git

# Config: $ssh runs a command on the remote host
ssh="ssh -p $dst_port $dst_user@$dst_host"

# Remote: make the remote directory, if needed.
# Remote: clone the github project, if needed
# Remote: git pull
$ssh "mkdir -p $dst_path; [ -e $dst_path_gem_name ] || git clone $git_deploy_link $dst_path_gem_name; cd $dst_path_gem_name && git pull"

