#!/bin/bash
set -o errexit

gem_name=`gemspec-cat | gemspec-to-gem-name`
gem_name_version=`gemspec-cat | gemspec-to-gem-name-version`

gem_version=`gemspec-cat | gemspec-to-gem-version`
gem_version_lt=$((${gem_version%%.*} + 1))

github_team_repo=`github-team-repo`
github_repo=${github_team_repo##*/}

file=README.md

###
#
# Header section
#
###

open="HEADER-OPEN"
shut="HEADER-SHUT"

badge0="[![Gem Version](https://badge.fury.io/rb/$gem_name.svg)](http://badge.fury.io/rb/$gem_name)\n"
badge1="[![Build Status](https://travis-ci.org/$github_team_repo.png)](https://travis-ci.org/$github_team_repo)\n"
badge2="[![Code Climate](https://codeclimate.com/github/$github_team_repo.png)](https://codeclimate.com/github/$github_team_repo)\n"
badge3="[![Coverage Status](https://coveralls.io/repos/$github_team_repo/badge.svg?branch=master&service=github)](https://coveralls.io/github/$github_team_repo?branch=master)\n"

link0="* Git: <https://github.com/sixarm/$github_repo>\n"
link1="* Doc: <http://sixarm.com/$gem_name/doc>\n"
link2="* Gem: <https://rubygems.org/gems/$gem_name>\n"
link3="* Contact: Joel Parker Henderson, <joel@sixarm.com>\n"
link4="* Project: [Changes](CHANGES.md), [License](LICENSE.md), [Contributing](CONTRIBUTING.md).\n"

text="\n\n$badge0$badge1$badge2$badge3\n$link0$link1$link2$link3$link4\n"
sed -i "/<!--$open-->/,/<!--$shut-->/c\<!--$open-->$text<!--$shut-->" "$file"

###
#
# Install section
#
###

open="INSTALL-OPEN"
shut="INSTALL-SHUT"

top0="## Install\n\n"

gem0="### Gem\n\n"
gem1="Run this command in your shell or terminal:\n\n"
gem2="    gem install $gem_name\n\n"
gem3="Or add this to your Gemfile:\n\n"
gem4="    gem '$gem_name'\n\n"

#sec0="### Command Line - More Security\n\n"
#sec1="Run these command in your shell or terminal:\n\n"
#sec2="    wget http://sixarm.com/sixarm.pem\n"
#sec3="    gem cert --add sixarm.pem && gem sources --add http://sixarm.com\n"
#sec4="    gem install $gem_name -v \">= $gem_version, < $gem_version_lt\" --trust-policy HighSecurity\n\n"

req0="### Require\n\n"
req1="To require the gem in your code:\n\n"
req2="    require '$gem_name'\n\n"

text="\n\n$top0$gem0$gem1$gem2$gem3$gem4$req0$req1$req2"
sed -i "/<!--$open-->/,/<!--$shut-->/c\<!--$open-->$text<!--$shut-->" "$file"
