#!/bin/sh
set -o errexit

##
# Lint all our gems.
#
# This lists all our gems that we're building,
# and iterates over them calling gemforge-link.
#
# Example:
#   gemforge-lint-all 
##

for dir in /home/sixarm/git/sixarm_ruby_*/*gemspec
do
  gem_dir=`dirname $dir`
  echo $gem_dir
  cd $gem_dir
  echo `pwd`
  gemforge-lint
done

